name: renovate aquaproj aqua registry auto merge
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    types:
      - opened
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: startWith("${{ github.ref_name }}", "renovate/aquaproj")
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Auto Merge
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh pr edit "${PR_URL}" --add-label "renovate"
          gh pr review --approve "${PR_URL}"
          gh pr edit "${PR_URL}" -t "(auto merged) ${PR_TITLE}"
          gh pr merge --auto --merge "${PR_URL}"
